name: lint and format

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --group dev
          python -m pip install .
      - name: Run ruff check
        run: ruff check --output-format=github src/ tests/ examples/
      - name: Run ruff format
        run: ruff format --diff src/ tests/ examples/
      - name: Run mypy
        run: python -m mypy src/ tests/ examples/
